name: sb_sgen
description: sellsbrothers.com static site generator
version: 0.1.0
homepage: https://www.sellsbrothers.com
author: Chris Sells <csells@sellsbrothers.com

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  yaml:
  jiffy:
  markdown:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
